version: '3.3'

services:
  backend:
    build: .
    ports:
      - "8888:8888"
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    build: ./client
    volumes:
      - frontend_build:/var/www/spotify-app/client/build
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  frontend_build:

networks:
  app-network:
    driver: bridge

