version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8888:8888"
    env_file:
      - .env
    # volumes:
      # - .:/server
      # - /server/node_modules
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
