version: '3.3'
services:
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email dnovsmith.ds20@gmail.com --agree-tos --no-eff-email --force-renewal -d dontasmith.com -d www.dontasmith.com

  backend:
    build: .
    restart: unless-stopped  # Ensures backend auto-restarts
    ports:
      - "8888:8888"
    env_file:
      - .env
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  frontend:
    build: ./client
    volumes:
      - web-root:/var/www/html  # Correctly map frontend build files
    depends_on:
      - backend
    environment:
      - DISABLE_HOST_CHECK=true
    networks:
      - app-network

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /var/www/html
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/donta/spotify-app/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge

